import Image from 'next/image'
import { ChannelShell, ChannelCard } from '@/components/cella-channel-shell'
import { MeasuredLink } from '@/components/cella-measured-link'
export const metadata = { title: 'New Zealand: the journey matters | Cella', robots: { index: false, follow: false } }
export default function NewZealand() {
  return <ChannelShell><section className="py-10"><p className="text-purple-300 tracking-widest">NEW ZEALAND / CAMPAIGN TRAVEL</p><h1 className="mt-4 max-w-3xl text-5xl sm:text-7xl">Make the journey<br/>part of the trip.</h1><p className="mt-6 max-w-2xl text-xl">I created travel content with Pure Milford and KiwiRail. These are two separate South Island experiences, not a packaged itinerary or a promise that they fit into one day.</p></section><Image src="/images/projects/milford-sound.jpg" width={1200} height={750} alt="Landscape from Cella’s New Zealand travel project" className="mb-8 max-h-[540px] w-full rounded-2xl object-cover"/>
    <div className="grid gap-6 sm:grid-cols-2"><ChannelCard title="Pure Milford"><p>Use my original campaign reel to see the experience I documented. Check departure point, transport inclusion, weather arrangements and cancellation terms for the exact product you book.</p><MeasuredLink event="travel_story_open" placement="nz_milford" href="https://www.instagram.com/reel/C_FfYv1qBgr/" className="inline-block py-3 text-purple-200 underline">Watch my original reel ↗</MeasuredLink></ChannelCard><ChannelCard title="TranzAlpine"><p>My KiwiRail project documented the train journey. Seat class, route, departure date and luggage conditions matter: compare the actual product, not just a scenic photo.</p><MeasuredLink event="travel_story_open" placement="nz_train" href="https://www.instagram.com/reel/C9qQOO8K51S/" className="inline-block py-3 text-purple-200 underline">Watch my original reel ↗</MeasuredLink></ChannelCard></div><p className="mt-8 text-lg text-white/70">Commercial relationship disclosed: this is campaign work. No bookable affiliate product is linked until the exact experience and approved traffic source have been verified.</p>
  </ChannelShell>
}
