import Link from "next/link"
import Image from "next/image"
import { ArrowDown, ArrowUpRight } from "lucide-react"
import { SiteHeader } from "@/components/site-header"
import { Footer } from "@/components/footer"
import { CoverVideo } from "@/components/cover-video"
import { BrandStories } from "@/components/brand-stories"
import { ScrollChoreography } from "@/components/scroll-choreography"
import { services } from "@/lib/services"
import { createPageMetadata } from "@/lib/seo"
export const metadata = createPageMetadata({ title: "CELLA | Content Creation & Creative Strategy Studio", description: "CELLA is a creative studio partnering with businesses and global brands on content creation, creative strategy and brand partnerships. Sydney and beyond.", path: "/" })
const brands = [["merivale-logo.png", "Merivale"], ["kitchenaid-logo.png", "KitchenAid"], ["mirvac-logo.svg", "Mirvac"], ["google-logo.webp", "Google"], ["nsw-placemaking-logo.png", "Placemaking NSW"], ["ninja-logo.png", "Ninja"]]
export default function Home() {
return <><SiteHeader cinematic /><main id="main-content" tabIndex={-1} className="cella-home cella-fluid"><ScrollChoreography />
<section className="cella-cover-hero studio-cover" aria-labelledby="hero-heading"><CoverVideo /><div className="cella-cover-shade" /><div className="cella-cover-copy"><p className="cella-eyebrow">Creative studio · Sydney & beyond</p><h1 id="hero-heading">Content creation.<br />Creative strategy.<br />Brand partnerships.</h1><p>CELLA is a creative studio partnering with businesses and global brands to develop content and campaigns shaped around their identity, audience and goals.</p><div className="cella-actions"><Link href="/contact" className="cella-button">Enquire now <ArrowUpRight size={18} aria-hidden="true" /></Link><a href="#work" className="cella-text-link">Explore the work <ArrowDown size={17} aria-hidden="true" /></a></div></div></section>
<section className="cella-brand-strip" aria-label="Selected brands CELLA has worked with"><p className="cella-eyebrow">Selected brand collaborations</p><div>{brands.map(([file,name]) => <Image key={name} src={`/images/brands/${file}`} alt={name} width={150} height={52} sizes="(max-width: 600px) 25vw, 150px" className="cella-brand-logo" />)}</div></section>
<section id="about" className="cella-section editorial-intro"><p className="cella-eyebrow">Your creative partner</p><div><h2>Your business.<br />A story with direction.</h2><p>We work with businesses, brands and agencies to turn a clear brief into content with personality. From the first idea to the final edit, the work is shaped around what makes your brand distinct and what you want to achieve.</p><p>Content creation and strategy, brought together for campaigns and ongoing partnerships.</p></div></section>
<section id="work" className="cella-section"><div className="cella-section-heading"><div><p className="cella-eyebrow">Selected work</p><h2>Brand stories.<br />Built with purpose.</h2></div><Link href="/portfolio" className="cella-text-link">Explore the work <ArrowUpRight size={17} /></Link></div><BrandStories /></section>
<section id="services" className="cella-section cella-services craft-services studio-services"><div className="cella-section-heading"><div><p className="cella-eyebrow">How we work together</p><h2>From the first idea.<br />Through every chapter.</h2></div><p className="cella-section-description">We start with your business, audience and goals. Together, we shape the creative direction, agree the scope and produce content with a clear role in your brand’s story.</p></div><div className="craft-service-links">{services.map(service => <Link key={service.href} href={`/contact?service=${encodeURIComponent(service.enquiry)}`}><div><span className="cella-eyebrow">{service.number}</span><h3>{service.title}</h3><p>{service.description}</p></div><ArrowUpRight size={25} aria-hidden="true" /></Link>)}<Link href="/contact?service=Brand%20Partnership"><div><span className="cella-eyebrow">03</span><h3>Brand partnerships</h3><p>Campaigns and ongoing collaborations through @cella.channel, connecting your brand with a personal approach to storytelling.</p></div><ArrowUpRight size={25} aria-hidden="true" /></Link></div></section>
<section className="cella-section editorial-quote"><p className="cella-eyebrow">A word from the other side of the brief</p><figure><blockquote>“Really enjoyed working with you… Videos are my favourite so far. Super authentic and warm.”</blockquote><figcaption>Justin · Kings Cross</figcaption></figure></section>
<section id="contact" className="cella-section editorial-cta"><p className="cella-eyebrow">Let’s work together</p><h2>What’s next<br />for your brand?</h2><p className="studio-cta-copy">Share your brief, goals and timing. Enquire for a detailed proposal shaped around your business.</p><Link href="/contact" className="cella-button">Enquire now <ArrowUpRight size={18} /></Link></section>
</main><Footer /></>
}
