import Link from "next/link"
import Image from "next/image"
import { ArrowDown, ArrowUpRight } from "lucide-react"
import { SiteHeader } from "@/components/site-header"
import { Footer } from "@/components/footer"
import { CoverVideo } from "@/components/cover-video"
import { FeaturedWork } from "@/components/featured-work"
import { ShopFeature } from "@/components/shop-feature"
import { services } from "@/lib/services"
import { createPageMetadata } from "@/lib/seo"
export const metadata = createPageMetadata({ title: "CELLA | Content Creation & Strategy, Sydney", description: "Content with personality. Strategy with purpose. Marcella creates video, photography and social strategy for hospitality, travel and lifestyle brands in Sydney and beyond.", path: "/" })
const brands = [["merivale-logo.png", "Merivale"], ["kitchenaid-logo.png", "KitchenAid"], ["mirvac-logo.svg", "Mirvac"], ["google-logo.webp", "Google"], ["nsw-placemaking-logo.png", "Placemaking NSW"], ["ninja-logo.png", "Ninja"]]
export default function Home() {
return <><SiteHeader /><main id="main-content" tabIndex={-1} className="cella-home">
<section className="cella-cover-hero" aria-labelledby="hero-heading"><CoverVideo /><div className="cella-cover-shade" /><div className="cella-cover-copy"><p className="cella-eyebrow">Content & strategy · Sydney & beyond</p><h1 id="hero-heading">A good story<br /><em>starts here.</em></h1><p>For places, people and brands<br />with something worth sharing.</p><div className="cella-actions"><Link href="/contact" className="cella-button">Work with me <ArrowUpRight size={18} /></Link><Link href="#work" className="cella-text-link">Explore the work <ArrowDown size={17} /></Link></div></div><div className="cella-cover-location">THE WORLD THROUGH THE CELLA LENS <span>Food. Travel. A little curiosity.</span></div></section>
<section className="cella-section editorial-intro"><p className="cella-eyebrow">A feeling, made into a story.</p><div><h2>Content with personality.<br /><em>Strategy with purpose.</em></h2><p>I’m Marcella. I help hospitality, travel and lifestyle brands show people what makes them special — through thoughtful content and a clear direction for social.</p></div></section>
<section className="cella-brand-strip" aria-label="Selected brands CELLA has worked with"><p className="cella-eyebrow">A few familiar names</p><div>{brands.map(([file,name]) => <Image key={name} src={`/images/brands/${file}`} alt={name} width={150} height={52} sizes="(max-width: 600px) 25vw, 150px" className="cella-brand-logo" />)}</div></section>
<section id="work" className="cella-section"><div className="cella-section-heading"><div><p className="cella-eyebrow">Seen, felt, remembered.</p><h2>A few good stories.</h2></div><Link href="/portfolio" className="cella-text-link">All work <ArrowUpRight size={17} /></Link></div><FeaturedWork /></section>
<section id="services" className="cella-section cella-services"><div className="cella-section-heading"><div><p className="cella-eyebrow">What I can help with</p><h2>Your story.<br /><em>Let’s give it direction.</em></h2></div><p className="cella-section-description">From the first idea to the final edit. Creative work shaped around your brand and the people you want to reach.</p></div><div className="cella-service-list">{services.map(service => <Link key={service.href} href={service.href} className="cella-service"><span>{service.number}</span><div><h3>{service.title}</h3><p>{service.description}</p></div><ArrowUpRight size={26} aria-hidden="true" /></Link>)}</div><Link href="/services" className="cella-text-link cella-services-link">Find your fit <ArrowUpRight size={17} /></Link></section>
<section id="about" className="cella-section editorial-about"><div className="editorial-portrait"><Image src="/images/editorial/marcella-dining.jpg" alt="Marcella enjoying an evening out" fill sizes="(max-width: 750px) 90vw, 45vw" /><span>A table, a story, a reason to stay.</span></div><div><p className="cella-eyebrow">The person behind the lens</p><h2>Hey, I’m<br /><em>Marcella.</em></h2><p>A Sydney creator with a curiosity for good food, memorable stays and places worth discovering.</p><p>I’m the person behind @cella.channel. I turn real experiences into stories that give people a reason to care — and brands a way to connect.</p><Link href="/about" className="cella-text-link">A little more about me <ArrowUpRight size={17} /></Link></div></section>
<ShopFeature />
<section className="cella-section editorial-quote"><p className="cella-eyebrow">A word from the other side of the brief</p><figure><blockquote>“Really enjoyed working with you… Videos are my favourite so far. Super authentic and warm.”</blockquote><figcaption>Justin · Kings Cross</figcaption></figure></section>
<section id="contact" className="cella-section editorial-cta"><p className="cella-eyebrow">Something in mind?</p><h2>Let’s make something<br /><em>worth sharing.</em></h2><Link href="/contact" className="cella-button">Tell me about it <ArrowUpRight size={18} /></Link></section>
</main><Footer /></>
}
