import { ChannelShell, ChannelCard } from '@/components/cella-channel-shell'
import { MeasuredLink } from '@/components/cella-measured-link'
export const metadata = { title: 'Sydney Date Nights: free sample | Cella', robots: { index: false, follow: false } }
const button = 'inline-block rounded-lg bg-purple-200 px-5 py-3 text-black underline-offset-4 hover:underline focus-visible:outline-4 focus-visible:outline-white'
export default function SydneyGuide() {
  return <ChannelShell><section className="max-w-3xl py-12"><p className="text-purple-300 tracking-widest">THE SYDNEY EDIT / FREE SAMPLE</p><h1 className="mt-4 text-5xl leading-tight sm:text-7xl">Where should we go?</h1><p className="mt-6 text-xl leading-relaxed text-white/80">Three different date nights, chosen from my actual visits. What I liked, what to check and a direct route to the venue.</p></section>
    <div className="grid gap-6">
      <ChannelCard title="RIVA, Rose Bay"><p>The lobster pasta and croquettes were my highlights, but I found it expensive. This is an occasion meal, not my budget pick. Collaboration visit.</p><p>The official 10 September menu lists lobster spaghetti at A$145 for two and croquettes at A$11 each. Two croquettes plus the shared pasta total A$167 before drinks and charges.</p><p>10% weekend and 15% public-holiday surcharges are listed. The venue states there is no wheelchair access.</p><MeasuredLink event="official_booking_open" placement="sample_riva" href="https://srghospitality.com.au/venue/riva/" className={button}>RIVA menu and reservations ↗</MeasuredLink></ChannelCard>
      <ChannelCard title="Vitelli’s Upstairs, Redfern"><p>Lasagne bites are the personally supported starting point. I loved the visits. Hosted dining.</p><p>The current sample menu lists fried lasagne bites with lemon at A$18. Other menu dishes are not automatically personal recommendations. The bar is walk-in; use the restaurant booking link for dinner.</p><p>A removable 5% gratuity is listed, replaced by 10% service for groups of eight or more. Check holiday charges and current opening dates.</p><MeasuredLink event="official_booking_open" placement="sample_vitellis" href="https://vitellisupstairs.com.au/eat" className={button}>Vitelli’s menu and reservations ↗</MeasuredLink></ChannelCard>
      <ChannelCard title="Island Radio, Redfern"><p>I loved the visits and the menu change. Hosted dining. I am keeping this recommendation about the overall experience rather than inventing a list of favourite dishes.</p><p>For a current menu reference, the A$88 per person banquet has a minimum of two. That is A$176 for two before drinks and charges, not a meal I am claiming to have tested.</p><p>The menu lists a removable 3% gratuity, 10% Sunday and 18% public-holiday surcharges, with different group-service arrangements.</p><MeasuredLink event="official_booking_open" placement="sample_island" href="https://www.islandradio.sydney/menus" className={button}>Island Radio menus ↗</MeasuredLink></ChannelCard>
    </div><section className="mt-10 rounded-2xl bg-purple-200 p-7 text-black"><h2 className="text-3xl">Would you use the full guide?</h2><p className="mt-4 text-lg">The first edition contains seven restaurant picks, decision notes, menu and booking links, and budget examples. A$19 is a proposed price, not an active offer. It is not on sale yet.</p><p className="mt-4 text-lg">If it sounds useful, open my Instagram and send “SYDNEY 19”. This is a manual conversation, not a waitlist, reservation or purchase. There is no automated delivery.</p><MeasuredLink event="guide_interest_open" placement="sydney_price_test" href="https://www.instagram.com/cella.channel/" className="mt-5 inline-block rounded-lg bg-black px-5 py-3 text-white">Open Cella on Instagram ↗</MeasuredLink></section>
  </ChannelShell>
}
